apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver # Name of the deployment
  namespace: webserver # Name of the namespace
  labels:
    app: webserver # Name of your application
spec:
  selector:
    matchLabels:
      app: webserver # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: webserver # Name of your application
    spec:
      containers:
      # Containers are the individual pieces of your application that you want
      # to run.
      - name: nginx # Name of the container
        image: nginx:latest # The image you want to run
        ports:
        # Ports are the ports that your application uses.
        - containerPort: 80 # The port that your application uses
        resources:
          limits:
            memory: 512Mi
            cpu: "1"